variable "component" {}
variable "env" {}
variable "vpc_id" {}
variable "server_app_port_sg_cidr" {}
variable "subnet_ids" {}
variable "instance_type" {}
variable "bastion_nodes" {}
variable "kms_key_id" {}
variable "zone_id" {}
